# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'UITEST.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#TODO:选择下载文件（不如直接写一个文件目录）
#TODO:idf安装过程
import sys
import os
from PyQt5 import QtWidgets
from UI import UITEST
import threading
import time
from Libs import varity, Serial, Files
Port = ""
Click = 0
Serial = Serial.Serial()
PortList = []
LastPortList = []
osStatues = 1
Files = Files.FilesClass()

def comBoxSelected():
    global Port
    global pyb
    print(Serial.comports[Ui.comboBox.currentIndex()])
    Port = Serial.comports[Ui.comboBox.currentIndex()]
    Files.ChangePort(Port)

def BoardAction():
    global Click
    CMD = ""
    osStatues = 0
    while True:
        if Click == 1:
            CMD = "esptool.py --port "+Port+" erase_flash"
            print(time.asctime())
            Ui.lineEdit.setText("Earsing Flash")
            OutPut = time.asctime()+"   Erasing complete"
            Ui.lineEdit.setText(OutPut)
            Click = 0
        elif Click == 2:
            CMD = "esptool.py --chip esp32 --port " + Port + " write_flash -z 0x1000 Framwork/ESP32_GENERIC-20231005-v1.21.0.bin"
            Click = 0
        if CMD != "":
            print(CMD)

        Click = 0
def Clicked():
    global Click
    Click = 1


def Window():#WindowReFlash
    global LastPortList
    while True:
       # print(osStatues)
        PortList = varity.q.get()
        if (PortList == LastPortList) == False:
            Ui.comboBox.clear()
            Ui.comboBox.addItems(PortList)
            LastPortList = PortList

#连接PyCharm
def ConnectToESPDevice():#如果可以连接到板子，并且成功执行代码，就不显示窗口，否则显示窗口让用户选择Port
    global Click
    Click = 3
    Files.ChangePort(Port)

#读取配置文件
def ReadConfig():
    with open('data.bin','r') as f:
        data = f
        print(data)
        if data !=0:
            MainWndow.show()
        f.close()

#下载固件
def DownLoadBoot():
    global Click
    Click = 2

def RunProgramme():
    global osStatues
    CMD = "python .\Libs\pyboard.py -d " + Port + " ./app.py"
    osStatues = os.system(CMD)
    print("osStatues",osStatues)
    if osStatues != 0:
        MainWndow.show()
# _QTWindows_#
app = QtWidgets.QApplication(sys.argv)
MainWndow = QtWidgets.QMainWindow()
Ui = UITEST.Ui_Dialog()
Ui.setupUi(MainWndow)
Ui.comboBox.currentIndexChanged.connect(comBoxSelected)
Ui.pushButton_3.clicked.connect(Clicked)
Ui.pushButton_2.clicked.connect(ConnectToESPDevice)
Ui.pushButton_4.clicked.connect(DownLoadBoot)
Ui.lineEdit.setReadOnly(True)
RunProgramme()
# _QTWindows_#

#_Thread_
GetSerial = threading.Thread(target=Serial.UpDatePortList)
WindowProc = threading.Thread(target=Window)
ClickProc = threading.Thread(target=BoardAction)
CTD = threading.Thread(target=ConnectToESPDevice)
#_Thread_

#CTD.start()
GetSerial.start()
ClickProc.start()
WindowProc.start()
#CTD.start()

sys.exit(app.exec())


